---
abstract: unknown
author:
  - 'Matthaeus Kiem <cuer2s@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Choose
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  Term::ReadKey: 0
  Text::LineFold: 0
  Unicode::GCString: 0
  perl: 5.010001
version: 1.073
