---
abstract: 'Choose items from a list.'
author:
  - 'Matthäus Kiem <cuer2s@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Choose
provides:
  Term::Choose:
    file: lib/Term/Choose.pm
    version: 1.003
  Term::Choose::GC:
    file: lib/Term/Choose/GC.pm
    version: 1.003
requires:
  Carp: 0
  Scalar::Util: 0
  Term::ReadKey: 2.3
  Unicode::GCString: 2012.04
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.003
